name: Check no committed secrets

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-no-committed-secrets:
    name: Check no committed secrets
    runs-on: k8s-x64-small
    steps:
      - name: Git Clone the Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
