name: Check no committed secrets

# Run when a pull request is opened or updated
on: pull_request

permissions:
  # Needed to clone the repository
  contents: read

jobs:
  check-no-committed-secrets:
    name: Check no committed secrets
    runs-on: k8s-arm64-small
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
